---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi hichem123/comingsoon-page
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t hichem123/comingsoon-page:{{ tag }} .

    - name: Push Image to dockerhub
      command: docker push hichem123/comingsoon-page:{{ tag }}

    - name: run container
      command: docker run -d --restart=always --name web-container -p 5000:80 hichem123/comingsoon-page:{{ tag }}

